# Generated by Django 2.2.2 on 2019-06-28 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Currency name')),
                ('current_value', models.DecimalField(decimal_places=5, max_digits=30, verbose_name='Actual rate')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(choices=[('B', 'buy'), ('S', 'sell')], max_length=4, verbose_name='Transaction option')),
                ('transaction_amount', models.DecimalField(decimal_places=5, max_digits=30, verbose_name='Purchase cost')),
                ('transaction_date', models.DateField(auto_now=True, verbose_name='Transaction date')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
